prod:
  enabled:           true

all:
  enabled:           true
  
  driver:
    class:           sfErrorNotifierDriverFile
    options:        
      path:          '%SF_LOG_DIR%/last-error.html'
  
  message:
    class:          sfErrorNotifierMessageHtml

#  driver:
#    class:           sfErrorNotifierDriverNativeMail
#    options:
#      to:            developer1@example.com,developer2@example.com
#      from:          mail-from@example.com