prod:
  enabled:           true

all:
  enabled:           false
  
  driver:
    class:           sfErrorNotifierDriverFile
    options:        
      path:          '%SF_LOG_DIR%/last-error.html'
      
#  driver:
#    class:           sfErrorNotifierDriverNativeMail
#    options:
#      to:            developer1@example.com,developer2@example.com
#      from:          mail-from@example.com
  
  message:
    class:          sfErrorNotifierMessageHtml